"""The deterministic calculation engine.

Financial math lives here, not in prose generated by a language model. Every
function takes provenanced inputs and returns a ``Calculated`` value that records
those inputs, so the number is reproducible and auditable. The model may *explain*
these figures; it never invents them.
"""

from .calculations import (
    cagr,
    emergency_fund_months,
    portfolio_weights,
    savings_rate,
)

__all__ = [
    "cagr",
    "savings_rate",
    "portfolio_weights",
    "emergency_fund_months",
]
